# Generated by Django 5.1.2 on 2024-11-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_votingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='myapp.elections')),
            ],
            options={
                'db_table': 'election_positions',
            },
        ),
        migrations.CreateModel(
            name='CandidatePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_positions', to='myapp.users')),
                ('election_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='myapp.electionposition')),
            ],
        ),
        migrations.AddField(
            model_name='votes',
            name='election_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.electionposition'),
        ),
    ]
