# Generated by Django 5.1.2 on 2024-11-26 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_electionposition_candidateposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='allow_self_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReferendumQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referendum_questions', to='myapp.elections')),
            ],
            options={
                'db_table': 'referendum_questions',
            },
        ),
        migrations.CreateModel(
            name='ReferendumOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.referendumquestion')),
            ],
            options={
                'db_table': 'referendum_options',
            },
        ),
    ]
