# Generated by Django 5.1.2 on 2024-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_referendumvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referendumvote',
            name='election',
        ),
        migrations.RemoveField(
            model_name='referendumvote',
            name='user',
        ),
        migrations.AddField(
            model_name='referendumvote',
            name='anonymous_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
