# Generated by Django 5.1.2 on 2024-11-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_referendumvote_election_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referendumvote',
            name='question_text',
        ),
        migrations.AddField(
            model_name='referendumvote',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.referendumquestion'),
        ),
    ]
