# Generated by Django 5.1.2 on 2024-11-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_elections_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='icon',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
