# Generated by Django 5.1.2 on 2024-11-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_elections_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
