# Generated by Django 5.1.2 on 2024-11-30 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_elections_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_options', models.JSONField(default=list)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='myapp.elections')),
            ],
            options={
                'db_table': 'election_approvals',
            },
        ),
    ]
