# Generated by Django 5.1.2 on 2024-12-03 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_electionapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.elections')),
            ],
        ),
    ]
