# Generated by Django 5.1.2 on 2024-12-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_withdrawaltoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaltoken',
            name='position_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.electionposition'),
        ),
    ]
