# Generated by Django 5.1.2 on 2024-12-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_users_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='is_launched',
            field=models.BooleanField(default=False),
        ),
    ]
