# Generated by Django 5.1.2 on 2024-12-18 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.electionposition'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('VOTE_ELIGIBILITY', 'Vote Eligibility'), ('CANDIDATE_REQUEST', 'Candidate Request'), ('OTHER_TYPE', 'Other Request')], max_length=50),
        ),
    ]
