# Generated by Django 5.1.2 on 2024-12-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_request_position_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('VOTE_ELIGIBILITY', 'Vote Eligibility'), ('CANDIDATE_REQUEST', 'Candidate Request'), ('WITHDRAW_REQUEST', 'Withdraw Request'), ('OTHER_TYPE', 'Other Request')], max_length=50),
        ),
    ]
