# Generated by Django 5.1.2 on 2025-01-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_elections_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutions',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
